[font]
normal = { family = "GeistMono Nerd Font Mono", style = "Regular" }

bold = { family = "GeistMono Nerd Font Mono", style = "Bold" }

italic = { family = "GeistMono Nerd Font Mono", style = "italic" }

bold_italic = { family = "GeistMono Nerd Font Mono", style = "Bold Italic" }

size = 11

offset = { x = 0, y = 0 }
