[font]
normal = { family = "DroidSansM Nerd Font Mono", style = "Regular" }

bold = { family = "DroidSansM Nerd Font Mono", style = "Bold" }

italic = { family = "DroidSansM Nerd Font Mono", style = "italic" }

bold_italic = { family = "DroidSansM Nerd Font Mono", style = "Bold Italic" }

size = 10.5

offset = { x = 0, y = 0 }
